---
- hosts: gluster_servers
  vars: 
    rhel7_interface: enp0s3
    default_interface: eth0
  tasks:
    - set_fact:
        other_servers: "{{ lookup('template', 'lookup.j2') | from_yaml }}"
        
    - debug:
        msg: "addresses to use: {{ other_servers | join(',') }}"
        
        
