---
language: python
python: "2.7"
sudo: required

env:
  - ANSIBLE_VERSION=1.9.6
  - ANSIBLE_VERSION=2.1.3
  - ANSIBLE_VERSION=latest

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  
