---
language: python
python: "2.7"
sudo: required

env:
  - ANSIBLE_VERSION=2.2
  - ANSIBLE_VERSION=latest

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

script:
  # Syntax check
  - ansible-playbook -i localhost, roles/Filebeat/test/test.yml --syntax-check
  - ansible-playbook -i localhost, roles/Filebeat/test/test.yml --connection=local
  - ansible-playbook -i localhost, roles/Logrotate/test/test.yml --syntax-check
  - ansible-playbook -i localhost, roles/Logrotate/test/test.yml --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
