---
#- include_role:
#  name: ../../common

- include_vars:
    file: vars/main.yml

- name: create logrotate configuration directory
  file:
    path: "{{ logrotate_include_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  become: yes
  tags:
  - logrotate

- name: setup logrotate configuration file
  template:
    src: logrotate.conf.j2
    dest: "{{ lr_main_config_file }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  tags:
  - logrotate

- name: create logrotate application configuration files
  template:
    src: application.j2
    dest: "{{ logrotate_include_dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - "{{ logrotate_applications }}"
  become: yes
  tags:
  - logrotate
